-- Answers in PostgreSQL
-- Soal A
SELECT * FROM Barang
WHERE HARGA_SATUAN > 10000
ORDER BY HARGA_SATUAN;

-- Soal B
SELECT * FROM Pelanggan
WHERE NAMA LIKE '%g%' AND ALAMAT = 'BANDUNG';

-- Soal C
SELECT t.KODE, t.TANGGAL, p.NAMA AS 'NAMA PELANGGAN', b.NAMA AS 'NAMA BARANG', t.JUMLAH_BARANG AS JUMLAH, b.HARGA_SATUAN AS 'HARGA SATUAN', 
(t.JUMLAH_BARANG * b.HARGA_SATUAN) AS TOTAL
FROM Transaksi t
JOIN Pelanggan p ON t.KODE_PELANGGAN = p.KODE
JOIN Barang b ON t.KODE_BARANG = b.KODE;

-- Soal D
SELECT p.NAMA AS 'NAMA PELANGGAN', SUM(t.JUMLAH_BARANG) AS JUMLAH, 
SUM(t.JUMLAH_BARANG * b.HARGA_SATUAN) AS 'TOTAL HARGA'
FROM Transaksi t
JOIN Pelanggan p ON t.KODE_PELANGGAN = p.KODE
JOIN Barang b ON t.KODE_BARANG = b.KODE
GROUP BY p.NAMA;

